services:
  supplier_app:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - ENDPOINT_URL=http://store-manager-api:5000/stocks/graphql
    volumes:
      - .:/app
    networks:
      - labo03-network

networks:
  labo03-network:
    driver: bridge
    external: true
